include (cmake/setup_cpm.cmake)

#cli11
CPMADDPACKAGE(
    NAME cli11
    GITHUB_REPOSITORY CLIUtils/CLI11
    GIT_TAG v2.4.2
    OPTIONS
    "CLI11_BUILD_EXAMPLES OFF"
)

CPMAddPackage(
  NAME asiocmake
  GIT_REPOSITORY "https://github.com/OlivierLDff/asio.cmake"
  GIT_TAG v1.2.0
  OPTIONS 
  "ASIO_TAG asio-1-30-2"
  "ASIO_USE_CPM ON"
)

CPMAddPackage(
    NAME fmt
    GITHUB_REPOSITORY fmtlib/fmt
    GIT_TAG 10.2.1
    OPTIONS
    "FMT_DOC OFF"
    "FMT_TEST OFF"
    "FMT_INSTALL OFF"
    "FMT_PEDANTIC OFF"
    "FMT_WERROR OFF"
    "FMT_USE_CCACHE OFF"
    "FMT_USE_FIND_PACKAGE OFF"
    "FMT_USE_CONFIG OFF"
    "FMT_USE_PKG_CONFIG OFF"
    "FMT_USE_CONAN OFF"
    "FMT_USE_VCPKG OFF"
    "FMT_USE_ASAN OFF"
    "FMT_USE_UBSAN OFF"
    "FMT_USE_MSAN OFF"
    "FMT_USE_TSAN OFF"
    "FMT_USE_CODE_ANALYSIS OFF"
    "FMT_USE_CPPCHECK OFF"
)

CPMADDPACKAGE(
#magic enum
    NAME magic_enum
    GITHUB_REPOSITORY Neargye/magic_enum
    GIT_TAG v0.9.7
    OPTIONS
    "MAGIC_ENUM_TESTS OFF"
    "MAGIC_ENUM_EXAMPLES OFF"
    "MAGIC_ENUM_INSTALL OFF"
    "MAGIC_ENUM_PEDANTIC OFF"
    "MAGIC_ENUM_WERROR OFF"
    "MAGIC_ENUM_USE_CCACHE OFF"
    "MAGIC_ENUM_USE_FIND_PACKAGE OFF"
    "MAGIC_ENUM_USE_CONFIG OFF"
    "MAGIC_ENUM_USE_PKG_CONFIG OFF"
    "MAGIC_ENUM_USE_CONAN OFF"
    "MAGIC_ENUM_USE_VCPKG OFF"
    "MAGIC_ENUM_USE_ASAN OFF"
    "MAGIC_ENUM_USE_UBSAN OFF"
    "MAGIC_ENUM_USE_MSAN OFF"
    "MAGIC_ENUM_USE_TSAN OFF"
    "MAGIC_ENUM_USE_CODE_ANALYSIS OFF"
    "MAGIC_ENUM_USE_CPPCHECK OFF"
)

CPMAddPackage(
#spdlog
    NAME spdlog
    GITHUB_REPOSITORY gabime/spdlog
    GIT_TAG v1.14.1
    OPTIONS
    "SPDLOG_BUILD_EXAMPLES OFF"
    "SPDLOG_BUILD_TESTS OFF"
    "SPDLOG_INSTALL OFF"
    "SPDLOG_FMT_EXTERNAL ON"
    
)

CPMAddPackage(
    NAME libzmq
    GITHUB_REPOSITORY zeromq/libzmq
    GIT_TAG v4.3.5
    OPTIONS "WITH_LIBSODIUM OFF"
    "WITH_PERF_TOOL OFF"
    "WITH_DOCS OFF"
    "WITH_TESTS OFF"
    "WITH_TOOLS OFF"
    "WITH_LIBUNWIND OFF"
    "WITH_SYSTEMD OFF"
    "WITH_OPENPGM OFF"
    "WITH_DRAFTS OFF"
    "WITH_CURVE OFF"
    "WITH_LZ4 OFF"
    "WITH_GSSAPI OFF"
    "WITH_LIBSODIUM OFF"
    "WITH_LIBZMQ_STATIC ON"
    "WITH_LIBZMQ_SHARED OFF"
    "WITH_TLS OFF"
    "WITH_VALGRIND OFF"
    "WITH_ASAN OFF"
    "WITH_UBSAN OFF"
    "WITH_MSAN OFF"
    "WITH_TSAN OFF"
    "WITH_CPACK OFF"
    "BUILD_SHARED OFF"
    "BUILD_TESTS OFF"
    "ZMQ_BUILD_TESTS OFF"
)


CPMAddPackage(
    NAME cppzmq
    GITHUB_REPOSITORY zeromq/cppzmq
    GIT_TAG v4.10.0
    OPTIONS
    "CPPZMQ_BUILD_TESTS OFF" 
)

CPMAddPackage( 
    NAME nlohmann_json

    GITHUB_REPOSITORY nlohmann/json
    GIT_TAG v3.11.3
)